// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://lwjmkjpjwgyckkflrnpe.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imx3am1ranBqd2d5Y2trZmxybnBlIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTI5NTIxODAsImV4cCI6MjA2ODUyODE4MH0.10ukGoD-3RjmdVFK7q-Ga01TMmWtjziz0oaGjwQlQVs";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});