// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://vqeoibxtwlcvuslxxryi.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InZxZW9pYnh0d2xjdnVzbHh4cnlpIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTI5Njg2NTUsImV4cCI6MjA2ODU0NDY1NX0.MSlbfNRUao0adwNw37JpxBYqfz8ULxibSB2IZQbIif0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});